---
title: "dashboard_template"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

# Interactive map over time (5/2021 - 5/2022) across US: 1. mask wearing 2. influenza admissions

## admisison ( 7-day average)
## mask wearing (last 7 days)

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(plotly)
```

Import data

```{r import_data}

merged_all <- 
read_csv("data/merged.csv") %>%
  janitor:: clean_names()  %>%
  select(-x1) %>%
  mutate(state = toupper(state))
  
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
date <- merged_all %>% distinct(date) %>% pull()

sliderInput(
  inputId = "date",
  label = h3("Date"),
  min = "2021-05-01" , max = "2022-05-01" , value = "2021-05-01"
)
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
  nyc_airbnb %>%
  filter(boro == input[["borough_choice"]],
         price >= input[["price_range"]][1],
         price <= input[["price_range"]][2],
         room_type == input[["room_choice"]]) %>%
  plot_ly(x = ~latitude, y = ~longitude, color = ~price, type = "scatter", mode = "markers", alpha = 0.5)
})



renderPrint({
  input[["borough_choice"]]
})

# df <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/2011_us_ag_exports.csv")


merged_all$hover <- with(merged_all, paste(state, '<br>'))

# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

fig <- plot_geo(merged_all, locationmode = 'USA-states')
fig <- fig %>% add_trace(
    z = ~admission, text = ~hover, locations = ~state,
    color = ~admission, colors = 'Purples'
  )
fig <- fig %>% colorbar(title = "Confirmed Cases per day (7-day average)")
fig <- fig %>% layout(
    title = 'Confirmed Influenza Admissions per day (7-day average) <br>(Hover for breakdown)',
    geo = g
  )

fig
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  nyc_airbnb %>% 
    filter(
      boro == input$boro_choice, 
      price %in% input$price_range[1]:input$price_range[2],
      room_type == input$room_choice) %>%
    count(neighbourhood) %>% 
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
    plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
})

renderPrint({
  input[["price_range"]]
})
```

### Chart C

```{r}
renderPrint({
  input[["room_choice"]]
})
```

