---
title: "Data Processing"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
```

## Create Final Dataset - Longitudinal

```{r}
e_mask_prop <-
read_csv("./Data/People_wearing_masks.csv") %>%
  janitor::clean_names()  %>%
  select (geo_value, time_value, value) %>%
  rename(maskwearing_prop=value, state=geo_value, date=time_value)

o_symptoms_prop <-
read_csv("./Data/Flu_like_symptoms.csv") %>%
  janitor:: clean_names()  %>%
  select(geo_value, time_value, value) %>%
  rename(symptom_prop=value,state=geo_value, date=time_value)

o_admission_prop <-
read_csv("./Data/influenza_admissions.csv") %>%
  janitor:: clean_names() %>%
  select(-x1) %>%
  select (geo_value, time_value, value) %>%
  rename(admission_prop = value, state=geo_value, date=time_value) %>%
  mutate(admission_prop = admission_prop * 100) # per 100 people

o_finances_prop <-
  read_csv("data/worried_finances.csv") %>%
  janitor::clean_names() %>%
  select(-x1) %>%
  select(geo_value, time_value, value) %>%
  rename(finances_prop = value, state=geo_value, date=time_value)

o_depression_prop <- 
  read.csv("Data/depression.csv") %>% 
  janitor:: clean_names() %>% 
  select (geo_value, time_value, value) %>% 
  rename(depression_prop =value, state = geo_value, date = time_value) %>%
  mutate(date = as.Date(date))
  
merge1 <-
  inner_join(
  x = e_mask_prop,
  y = o_admission_prop,
  by = c("state", "date"),
  all.x = TRUE) 

merge2 <-
  inner_join(
    x = o_symptoms_prop,
    y = merge1,
    by = c("state", "date"),
    all.x = TRUE)
  
merge3 <-
  inner_join(
  x = o_finances_prop,
  y = merge2,
  by = c("state", "date"),
  all.x = TRUE)

merge4 <-
  inner_join(
    x = merge3,
    y = o_depression_prop,
  by = c("state", "date"),
  all.x = TRUE) %>%
  mutate(state = toupper(state))

state <- setNames(as.list(datasets::state.name),datasets::state.abb) %>% 
  as.tibble() %>%
  pivot_longer(AL:WY, names_to = "state", values_to = "state_full")

merge5 <- merge4 %>%
  full_join(state, by = "state") %>%
  relocate(state_full, .after = state) %>%
  mutate(state_full = ifelse(is.na(state_full), "District of Columbia", state_full))

write.csv(merge5,"data/final_long.csv" )

```

## Create Final Dataset - Annual Average

```{r}
e_mask_avg <- 
read_csv("./Data/People_wearing_masks.csv") %>%
  janitor:: clean_names()  %>%
  select (geo_value, time_value, value) %>%
  group_by(geo_value) %>%
  summarize(avg_mask = mean(value))

o_admission_avg <-
read_csv("./Data/influenza_admissions.csv") %>%
  janitor:: clean_names() %>%
  select(geo_value, time_value, value) %>%
  mutate(value = value * 100) %>%
  group_by(geo_value) %>%
  summarize(avg_admission = mean(value))

o_symptoms_avg <-
read_csv("./Data/Flu_like_symptoms.csv") %>%
  janitor:: clean_names() %>%
  select(geo_value, time_value, value) %>%
  group_by(geo_value) %>%
  summarize(avg_symptom = mean(value))

o_finances_avg <-
  read_csv("data/worried_finances.csv") %>%
  janitor:: clean_names() %>%
  select (geo_value, time_value, value) %>%
  group_by(geo_value) %>%
  summarize(avg_finances = mean(value))

  
o_depression_avg <- read.csv("Data/depression.csv") %>% 
  janitor:: clean_names()  %>% 
  select (geo_value, time_value, value) %>% 
  group_by(geo_value) %>% 
  summarize(avg_depression = mean(value))

merge1_avg <-
  inner_join(
  x = e_mask_avg,
  y = o_admission_avg,
  by = c("geo_value"),
  all.x = TRUE) 

merge2_avg <-
  inner_join(
  x = merge1_avg,
  y = o_symptoms_avg,
  by = c("geo_value"),
  all.x = TRUE) 

merge3_avg <-
  inner_join(
  x = merge2_avg,
  y = o_finances_avg,
  by = c("geo_value"),
  all.x = TRUE) 

merge4_avg <-
  inner_join(
  x = merge3_avg,
  y = o_depression_avg,
  by = c("geo_value"),
  all.x = TRUE) %>%
  mutate(state = toupper(geo_value)) %>%
  relocate(state, .before = avg_mask) %>%
  select(-geo_value)

state <- setNames(as.list(datasets::state.name), datasets::state.abb) %>% 
  as.tibble() %>%
  pivot_longer(AL:WY, names_to = "state", values_to = "state_full")

merge5_avg <- merge4_avg %>%
  full_join(state, by = "state") %>%
  relocate(state_full, .after = state) %>%
  mutate(state_full = ifelse(is.na(state_full), "District of Columbia", state_full))

write.csv(merge5_avg,"data/final_avg.csv" )

```
