---
title: "Customizable Map & Model"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    orientation: rows
    vertical_layout: fill
    source_code: embed
    navbar:
        - { icon: "fa-home", href: "https://mingeechoi.github.io/P8105-final-project-proposal/", align: right }
---
  
```{r setup, include=FALSE}
# rm(list=ls())
library(flexdashboard)
library(tidyverse)
library(broom)
library(geepack)
library(shiny)
library(plotly)
```


Map
=========================================

Column {.sidebar}
-----------------------------------------------------------------------
  
Please select a variable's annual average to be mapped by state. 

#### Variable of Interest
```{r}
avg_df <- read.csv("https://raw.githubusercontent.com/mingeechoi/P8105-final-project-proposal/main/Data/final_avg.csv") %>% select(everything(), - X)

var_list <- colnames(avg_df)[3:7]

selectInput(
  "var_choice","Select variable of interest",
  choices = var_list, selected = "avg_mask")

```



Column 
-----------------------------------------------------------------------
  
### Plotly Map for Variable of Interest

```{r}


renderPlotly({ 
final_avg <- avg_df %>% select(1,2,input$var_choice)
colnames(final_avg)[3] <- "selected_v"
  
final_avg$hover1 <- with(final_avg, paste(state_full, '<br>'))

# give state boundaries a white border
l1 <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g1 <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

title_var <- data.frame(matrix(ncol = 2, nrow = 5))
title_var[,1]<-var_list
title_var[,2]<-c("Annual Average Estimated Percentage of Wear a Mask Most or All of the Time in public for the Past 7 Days",
                 "Annual Average Estimated Percentage of Adult and Pediatric Hospital Admissions with Confirmed Influenza for the Past 7 Days",
                 "Annual Average Estimated Percentage of Self-Reporting Influenza-like Symptoms for the Past 7 Days",
                 "Annual Average Estimated Percentage of Being very or somewhat Worried about Household Finances for the Next Month",
                 "Annual Average Estimated Percentage of Feeling Depressed for Most or All of the Past 7 Days")
colnames(title_var) <- c('var_in', 'title_in')

title_cust <- as.character(title_var %>% filter(var_in==input$var_choice) %>% select(title_in))


fig1 <- plot_geo(final_avg, locationmode = 'USA-states')
fig1 <- fig1 %>% add_trace(
    z = ~selected_v, text = ~hover1, locations = ~state,
    color = ~selected_v, colors = 'Blues'
  )
fig1 <- fig1 %>% colorbar(title = "Percentage %")
fig1 <- fig1 %>% layout(
    title = paste0('May 2021 - May 2022 ', title_cust,' <br> (Hover for breakdown)'),
    geo = g1
  )
})

```


Model with selected outcome
=========================================

Column {.sidebar}
-----------------------------------------------------------------------
  
Please feel free to explore the association variations in different states

#### Model Parameter Input

```{r import}
comp_df <- read.csv("https://raw.githubusercontent.com/mingeechoi/P8105-final-project-proposal/main/Data/final_long.csv")

states <- unique(comp_df$state_full)
```


```{r}
selectInput(
  "outcome_choice","Select outcome of interest",
  choices = c("admission","symptom"), selected = "admission")

selectInput(
  "cov_choice","Select covariates of interest",
  choices = c("finances_prop","finances_prop + maskwearing_prop*finances_prop",
              "depression_prop", "depression_prop + maskwearing_prop*depression_prop",
              "finances_prop + depression_prop",
              "finances_prop + depression_prop + finances_prop*depression_prop",
              "All Interactions/Full Model"), 
  selected = "finances_prop + depression_prop")

selectInput(
  "table_bin","Choose whether want National Model (takes 30S+ to run if inlcuded)",
  choices = c("Show National Model", "Don't Show National Model"), selected = "Don't Show National Model")

selectInput(
  "state_choice","Select states of interest",
  choices = states, selected = c("Alaska","Colorado","New York"),multiple=TRUE)

dateRangeInput("input_date", "Date range",
               start = "2021-05-01",end = "2022-05-01",
               min = "2021-05-01",max = "2022-05-01")


```



Row {.tabset .tabset-fade data-height=650}
-----------------------------------------------------------------------
  
### Selected States Exposure vs. Outcome of Interest
  
```{r}

analysis_df <- comp_df %>% mutate(date=as.Date(date),state=as.factor(state_full)) %>% arrange(state,date) %>% 
  select(- X,- state_full,everything())

renderPlotly({ 

   plot_df =
    analysis_df %>% 
    filter(
      state %in% input$state_choice &
      date>=as.Date(input$input_date[1]) & date<=as.Date(input$input_date[2]))%>%
      mutate(text_label = str_c("State: ", state, '\ndate: ', date))
  
  if(input$outcome_choice=="admission"){
    plot_df %>% plot_ly(
      x = ~maskwearing_prop, y = ~admission_prop, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~state, text = ~text_label)%>%
  layout(title = 'Maskwearing Rate vs. Influenza Admission',  xaxis = list(title = 'Maskwearing Rate (%)'), 
         yaxis = list(title = 'Influenza Admission (%)'), legend = list(title=list(text='<b> State of Interest </b>')))
  }else if (input$outcome_choice=="symptom"){
        plot_df %>% plot_ly(
      x = ~maskwearing_prop, y = ~symptom_prop, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~state, text = ~text_label)%>%
  layout(title = 'Maskwearing Rate vs. Influenza Symptom',  xaxis = list(title = 'Maskwearing Rate (%)'), 
         yaxis = list(title = 'Influenza Symptom (%)'), legend = list(title=list(text='<b> State of Interest </b>')))
  }
  
})
```

### National Exposure vs. Outcome of Interest

```{r}

renderPlotly({ 

   plot_df =
    analysis_df %>% 
    filter(
      date>=as.Date(input$input_date[1]) & date<=as.Date(input$input_date[2]))%>%
      mutate(text_label = str_c("State: ", state, '\ndate: ', date))
  
  if(input$outcome_choice=="admission"){
    plot_df %>% plot_ly(
      x = ~maskwearing_prop, y = ~admission_prop, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~state, text = ~text_label)%>%
  layout(title = 'Maskwearing Rate vs. Influenza Admission',  xaxis = list(title = 'Maskwearing Rate (%)'), 
         yaxis = list(title = 'Influenza Admission (%)'), legend = list(title=list(text='<b> State of Interest </b>')))
  }else if (input$outcome_choice=="symptom"){
        plot_df %>% plot_ly(
      x = ~maskwearing_prop, y = ~symptom_prop, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~state, text = ~text_label)%>%
  layout(title = 'Maskwearing Rate vs. Influenza Symptom',  xaxis = list(title = 'Maskwearing Rate (%)'), 
         yaxis = list(title = 'Influenza Symptom (%)'), legend = list(title=list(text='<b> State of Interest </b>')))
  }
  
})
```


Row {data-height=350}
-----------------------------------------------------------------------
### State Model Estimates

```{r}

shiny_input_model <- function(outcome, l_date, u_date, s_state, s_cov, b_nation){
  cov_in<-as.character(s_cov)
  
  if (outcome=="admission"){
    model_formula <- formula(paste0("admission_prop ~ maskwearing_prop + ",cov_in))
  }else if (outcome=="symptom"){
    model_formula <- formula(paste0("symptom_prop ~ maskwearing_prop + ", cov_in))
  }
  
  
  if (b_nation=="state"){
    temp_df<-analysis_df %>% filter(state_full %in% s_state & date>=as.Date(l_date) & date<=as.Date(u_date))
    out_table <- geeglm(formula=model_formula, data=temp_df, id=state,
                        family=gaussian("identity"),corstr="exchangeable",std.err = "san.se") %>% 
      broom::tidy() 
  } else if (b_nation=="nation"){
    temp_df<-analysis_df %>% filter(date>=as.Date(l_date) & date<=as.Date(u_date))
    out_table <- geeglm(formula=model_formula, data=temp_df, id=state,
                        family=gaussian("identity"),corstr="exchangeable",std.err = "san.se") %>% 
      broom::tidy() 
  }

  return(out_table)
}


renderTable({
  if (as.character(input$cov_choice) == "All Interactions/Full Model") {cov_input <- "finances_prop + depression_prop + maskwearing_prop*finances_prop + maskwearing_prop*depression_prop + finances_prop*depression_prop + maskwearing_prop*finances_prop*depression_prop"}
  else {cov_input <- as.character(input$cov_choice)}
  
  shiny_input_model(outcome=input$outcome_choice, l_date=input$input_date[1], u_date=input$input_date[2], s_state=input$state_choice, s_cov=cov_input, b_nation="state")
},digits=5)
```


### National Model Estimate

```{r}
uiOutput("dynamic")

output$dynamic <- renderUI({ 
  if (as.character(input$table_bin)=="Show National Model") tableOutput("table")
  else textOutput("text")
})

output$table <- renderTable({
    if (as.character(input$cov_choice) == "All Interactions/Full Model") {cov_input <- "finances_prop + depression_prop + maskwearing_prop*finances_prop + maskwearing_prop*depression_prop + finances_prop*depression_prop + maskwearing_prop*finances_prop*depression_prop"}
  else {cov_input <- as.character(input$cov_choice)}
  
  shiny_input_model(outcome=input$outcome_choice, l_date=input$input_date[1], u_date=input$input_date[2], s_state=input$state_choice, s_cov=cov_input, b_nation="nation")
},digits=5)
output$text <- renderText({ "Chose not to show National Estimates. Change input selection and please wait ~30s for the table to be produced." })


```


